services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=kerry!1234
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    